if(EXISTS "C:/Projects/Stochastic-Differential-Equations/Tests/run_tests[1]_tests.cmake")
  include("C:/Projects/Stochastic-Differential-Equations/Tests/run_tests[1]_tests.cmake")
else()
  add_test(run_tests_NOT_BUILT run_tests_NOT_BUILT)
endif()
